# Generated by Django 5.0.4 on 2024-04-08 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DIG', 'Digital'), ('MUR', 'Mural'), ('H2O', 'Water Color'), ('PAST', 'Pastel'), ('CRY', 'Acrylic'), ('OIL', 'Oil'), ('INK', 'Ink'), ('PRI', 'Print Making'), ('CHA', 'Charcoal'), ('PHO', 'Photography'), ('SCU', 'Sculpture'), ('MIX', 'Mixed Media'), ('COL', 'Collage'), ('OTH', 'Others')], default='DIG', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IMP', 'Impressionism'), ('CUB', 'Cubism'), ('SUR', 'Surrealism'), ('REA', 'Realism'), ('ABS', 'Abstract'), ('ROM', 'Romanticism'), ('ART', 'Art Nouveau'), ('POP', 'Pop Art'), ('pos', 'Post Modernism'), ('MIN', 'Minimalism'), ('CON', 'Contemporary'), ('THA', 'Thangka'), ('OTH', 'Others')], default='IMP', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=750)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medium', models.ManyToManyField(to='main_app.medium')),
                ('style', models.ManyToManyField(to='main_app.style')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=280)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.art')),
            ],
        ),
    ]
