# Generated by Django 5.0.4 on 2024-04-09 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Art Creation Date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Comment Posting Date'),
        ),
        migrations.RemoveField(
            model_name='art',
            name='medium',
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('IMP', 'Impressionism'), ('CUB', 'Cubism'), ('SUR', 'Surrealism'), ('REA', 'Realism'), ('ABS', 'Abstract'), ('ROM', 'Romanticism'), ('ART', 'Art Nouveau'), ('POP', 'Pop Art'), ('POS', 'Post Modernism'), ('MIN', 'Minimalism'), ('CON', 'Contemporary'), ('THA', 'Thangka'), ('OTH', 'Others')], default='IMP', max_length=75),
        ),
        migrations.AddField(
            model_name='art',
            name='medium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_app.medium'),
            preserve_default=False,
        ),
    ]
