# Generated by Django 5.0.4 on 2024-04-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_comment_options_comment_user'),
        ('main_app', '0003_alter_profile_user'),
    ]

    operations = [
    ]
