# Generated by Django 5.0.4 on 2024-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20240410_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(choices=[('DIG', 'Digital'), ('MUR', 'Mural'), ('H2O', 'Water Color'), ('PAST', 'Pastel'), ('CRY', 'Acrylic'), ('OIL', 'Oil'), ('INK', 'Ink'), ('PRI', 'Print Making'), ('CHA', 'Charcoal'), ('PHO', 'Photography'), ('SCU', 'Sculpture'), ('MIX', 'Mixed Media'), ('COL', 'Collage'), ('DRAW', 'Drawing'), ('TXT', 'Textile Art'), ('CER', 'Ceramics'), ('PERM', 'Performance Art'), ('INST', 'Installation Art'), ('GLASS', 'Glass Art'), ('MTL', 'Metal Work'), ('LEAT', 'Leather Work'), ('PEP', 'Paper Art / Origami'), ('MOS', 'Mosaic'), ('BOD', 'Body Art / Tattoo'), ('SND', 'Sound Art / Music'), ('OTH', 'Other')], default='DIG', max_length=75),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('IMP', 'Impressionism'), ('CUB', 'Cubism'), ('SUR', 'Surrealism'), ('REA', 'Realism'), ('ABS', 'Abstract'), ('ROM', 'Romanticism'), ('ART', 'Art Nouveau'), ('POP', 'Pop Art'), ('POS', 'Post Modernism'), ('MIN', 'Minimalism'), ('CON', 'Contemporary'), ('THA', 'Thangka'), ('OTH', 'Other')], default='IMP', max_length=75),
        ),
    ]
