# Generated by Django 5.0.4 on 2024-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment_profile_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Valuation'),
        ),
    ]
