# Generated by Django 5.0.4 on 2024-04-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment_profile_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.art')),
                ('medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.medium')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.style')),
            ],
            options={
                'unique_together': {('artwork', 'style', 'medium')},
            },
        ),
    ]
