# Generated by Django 5.0.4 on 2024-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_art_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(choices=[('DIG', 'Digital Art'), ('MUR', 'Mural / Graffiti'), ('H2O', 'Water Color'), ('PAS', 'Pastel'), ('ACR', 'Acrylic'), ('OIL', 'Oil Painting'), ('INK', 'Ink / Sumi-e'), ('PRI', 'Print Making'), ('CHA', 'Charcoal'), ('PHO', 'Photography'), ('SCU', 'Sculpture'), ('MIX', 'Mixed Media'), ('COL', 'Collage'), ('DRW', 'Drawing'), ('TXT', 'Textile Art / Fiber Arts'), ('CER', 'Ceramics'), ('PERF', 'Performance Art'), ('INS', 'Installation Art'), ('GLS', 'Glass Art'), ('MTL', 'Metal Work'), ('LTR', 'Leather Work'), ('PAP', 'Paper Art / Origami'), ('MOS', 'Mosaic'), ('BOD', 'Body Art / Tattoo'), ('SND', 'Sound Art / Music'), ('TYP', 'Typography'), ('OTH', 'Other')], default='DIG', max_length=75),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('IMP', 'Impressionism'), ('CUB', 'Cubism'), ('SUR', 'Surrealism'), ('REA', 'Realism'), ('ABS', 'Abstract'), ('ROM', 'Romanticism'), ('ART', 'Art Nouveau'), ('POP', 'Pop Art'), ('POS', 'Post Modernism'), ('MIN', 'Minimalism'), ('CON', 'Contemporary'), ('THA', 'Thangka'), ('PIX', 'Pixel Art'), ('STR', 'Street Art'), ('BOT', 'Botanical'), ('CON', 'Contemporary'), ('CLA', 'Classical'), ('POR', 'Portrait'), ('EXP', 'Experimental'), ('SKE', 'Sketch'), ('VIN', 'Vintage'), ('NAR', 'Narrative'), ('KNI', 'Knit / Crochet'), ('QUI', 'Quilting / Weaving'), ('POR', 'Porcelain / Stoneware'), ('THE', 'Theatrical'), ('FOL', 'Paper Folding / Papercraft'), ('TOO', 'Tattoo / Henna'), ('MUS', 'Music'), ('SOU', 'Interactive Sound Installation'), ('OTH', 'Other')], default='IMP', max_length=75),
        ),
    ]
