# Generated by Django 5.0.4 on 2024-04-14 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_medium_name_alter_style_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Creation/Performance Date'),
        ),
    ]
