# Generated by Django 5.0.4 on 2024-04-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_art_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('ABS', 'Abstract'), ('ART', 'Art Nouveau'), ('BOT', 'Botanical'), ('CLA', 'Classical'), ('CON', 'Contemporary'), ('CUB', 'Cubism'), ('EXP', 'Experimental'), ('FOL', 'Paper Folding / Papercraft'), ('IMP', 'Impressionism'), ('KNI', 'Knit / Crochet'), ('MIN', 'Minimalism'), ('MUS', 'Music'), ('NAR', 'Narrative'), ('PIX', 'Pixel Art'), ('POP', 'Pop Art'), ('POR', 'Portrait'), ('POT', 'Porcelain / Stoneware'), ('POS', 'Post Modernism'), ('REA', 'Realism'), ('ROM', 'Romanticism'), ('SKE', 'Sketch'), ('SOU', 'Interactive Sound Installation'), ('STR', 'Street Art'), ('SUR', 'Surrealism'), ('THE', 'Theatrical'), ('THA', 'Thangka'), ('TOO', 'Tattoo / Henna'), ('QUI', 'Quilting / Weaving'), ('VIN', 'Vintage'), ('OTH', 'Other')], default='ABS', max_length=75),
        ),
    ]
